name: build with NDK toolchains

on:
  workflow_dispatch:
  push:
    tags: ['*']

env:
  api_version: 28 # min. 21
  ndk: r28 # android-ndk-$ndk-linux.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zerotier-magisk
        uses: actions/checkout@v4

      - name: Get latest ZeroTier release tag
        id: ztversion
        run: echo "tag=$(curl -fsSL https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest | jq -r .tag_name)" >> "$GITHUB_OUTPUT"

      - name: Checkout ZeroTierOne
        uses: actions/checkout@v4
        with:
          repository: zerotier/ZeroTierOne
          ref: ${{ steps.ztversion.outputs.tag }}
          path: ZeroTierOne

      - name: Checkout libnatpmp
        uses: actions/checkout@v4
        with:
          repository: miniupnp/libnatpmp
          path: libnatpmp

      - id: commit
        uses: prompt/actions-commit-hash@v3

      - name: Prepare NDK Toolchain
        run: |
          wget -qO ndk.zip https://dl.google.com/android/repository/android-ndk-$ndk-linux.zip
          unzip -qq ndk.zip "android-ndk-$ndk/toolchains/*" && rm ndk.zip -f

      - name: Patch ZeroTier for Cross-Compile
        run: |
          pip3 install toml
          python3 build/patch.py

      - name: Build for AArch64
        run: |
          PATH=`pwd`/android-ndk-$ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          NDK_ROOT=`pwd`/android-ndk-$ndk/toolchains/llvm/prebuilt/linux-x86_64

          CC=aarch64-linux-android$api_version-clang
          CXX=aarch64-linux-android$api_version-clang++

          cd libnatpmp
          make clean
          make --silent CC=$CC natpmpc-shared
          cd ..

          cd ZeroTierOne
          make clean
          make --silent -j $(nproc) ZT_DEBUG=0 ZT_SSO_SUPPORTED=0 CC=$CC CXX=$CXX LDFLAGS="-L../libnatpmp" DEFS="-I../libnatpmp -D__GLIBC__=0"
          cd ..

          mkdir -p magisk/zerotier/lib
          cp ZeroTierOne/zerotier-one magisk/zerotier
          cp $NDK_ROOT/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so magisk/zerotier/lib

      - name: Upload AArch64
        uses: actions/upload-artifact@v4
        with:
          name: zerotier-magisk-aarch64-ndk-zt${{ steps.ztversion.outputs.tag }}-${{ steps.commit.outputs.short }}
          path: magisk/

      - name: Package AArch64 module zip
        run: |
          cd magisk
          zip -r ../zerotier-magisk-aarch64-ndk-${{ github.ref_name }}.zip .
          cd ..

      - name: Build for Arm
        run: |
          PATH=`pwd`/android-ndk-$ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          NDK_ROOT=`pwd`/android-ndk-$ndk/toolchains/llvm/prebuilt/linux-x86_64

          CC=armv7a-linux-androideabi$api_version-clang
          CXX=armv7a-linux-androideabi$api_version-clang++

          cd libnatpmp
          make clean
          make CC=$CC natpmpc-shared
          cd ..

          cd ZeroTierOne
          mv make-linux.mk.arm.ndk make-linux.mk
          make clean
          make --silent -j $(nproc) ZT_DEBUG=0 ZT_SSO_SUPPORTED=0 CC=$CC CXX=$CXX LDFLAGS="-L../libnatpmp" DEFS="-I../libnatpmp -D__GLIBC__=0"
          cd ..

          cp ZeroTierOne/zerotier-one magisk/zerotier/
          cp $NDK_ROOT/sysroot/usr/lib/arm-linux-androideabi/libc++_shared.so magisk/zerotier/lib

      - name: Upload Arm
        uses: actions/upload-artifact@v4
        with:
          name: zerotier-magisk-arm-ndk-zt${{ steps.ztversion.outputs.tag }}-${{ steps.commit.outputs.short }}
          path: magisk/

      - name: Package Arm module zip
        run: |
          cd magisk
          zip -r ../zerotier-magisk-arm-ndk-${{ github.ref_name }}.zip .
          cd ..

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          files: zerotier-magisk-*.zip
